### ISSUE TITLE
Cambio a IP statica con ansible no reinicia el servidor

### ISSUE THREAD

**Issue by jmmirand** [jmmirand/cluster-raspberrry#1]
Cuando cambio el fichero a mano , el servidor arranca y se le asigna la nueva ip sin problemas.

Cuando lo hago con el ansible no arranca.

``` yaml
    - name: Template a file to /etc/netplan/50-cloud-init.yaml
      template:
        src: 50-cloud-init.yaml
        dest: /etc/netplan/50-cloud-init.yaml
      become: yes
```

50-cloud-init.yaml
``` yaml
# This file is generated from information provided by the datasource.  Changes
# to it will not persist across an instance reboot.  To disable cloud-init's
# network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
    ethernets:
        eth0:
            dhcp4: false
            optional: true
            addresses:
              - {{ new_ip }}/24
            nameservers:
              addresses: [8.8.8.8,4.4.4.4]

    version: 2
```
y la variable la recupera del playbook
``` 
[workers-not-prepared]
192.168.1.62 hostname=worker01 new_ip=191.168.1.11
192.168.1.63 hostname=worker02 new_ip=191.168.1.12
```

si lo pongo a mano funciona

``` yml
network:
    ethernets:
        eth0:
            dhcp4: false
            optional: true
            addresses:
              - 192.168.1.10/24
            nameservers:
              addresses: [8.8.8.8,4.4.4.4]

    version: 2
```
